"""Render separately classified kinetic and conformer claims from audit evidence."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
GREEN='IUPAC Green Book (2008/2012), pp.45–46,65–67: https://iupac.org/wp-content/uploads/2019/05/IUPAC-GB3-2012-2ndPrinting-PDFsearchable.pdf'
NIST='NIST CODATA2022: https://physics.nist.gov/cuu/Constants/Table/allascii.txt'
CREST='CREST official --temp documentation and frozen v2.12 cregen.f90: https://crest-lab.github.io/crest-docs/page/documentation/keywords.html'
claims=[
('C01','Eyring rate arithmetic implements the activation-free-energy equation.',GREEN+'; '+NIST,'k=κkBT/h exp(-ΔG‡/RT); κ=1; absolute ΔG in kcal/mol, T inK; first-order units.','src/kinetics/eyring.rs::calculate_rate_constant','75-digit Decimal equation on frozen f32 inputs over temperature/barrier grid.','VERIFIED WITH NUMERICAL LIMIT','Normal-rate subset maximum relative error 6.9231e-8; subnormal and extreme failures separately retained.','High','Equation correctness does not identify a physical barrier or establish transition-state assumptions.'),
('C02','Physical constants and kcal/Hartree conversion are accurate.',NIST,'kB/h/NA exact SI; R=kBNA/4184; Hartree energy fromCODATA.','src/kinetics/eyring.rs constants; scripts/stericx_quantum.py constants','Independent Decimal arithmetic from primary constants.','VERIFIED WITH NUMERICAL LIMIT','R truncation relative difference ≈3.22e-10; Hartree conversion difference ≈2.03e-10 kcal mol^-1 Hartree^-1.','High','Numerical effects generally smaller than f32 rounding; physical energy-model errors not tested by constants.'),
('C03','Zero ΔΔG gives equal R:S and reversing sign exchanges preference.',GREEN,'ΔΔG=G‡S−G‡R, common reactant and equal pathway prefactors; zero→50:50.','src/kinetics/eyring.rs::product_ratio','Independent two-pathway rates with common energy shift, signed grid and signed zero.','VERIFIED WITH NUMERICAL LIMIT','R/S max error 3.7596e-6 percentage points; zero and sign symmetry observed.','High','This algebraic convention cannot infer the absolute enantiomer from unsigned experimental ee.'),
('C04','Enantiomeric excess arithmetic follows the two-pathway populations.',GREEN,'Absolute ee=100|pR−pS|; signed ee, if requested, must retain configuration convention.','src/kinetics/eyring.rs::calculate_enantiomeric_excess','Independent pathway probabilities, zero and small/large differences.','VERIFIED WITH NUMERICAL LIMIT','Max absolute error 7.5191e-6 percentage points; tiny ee and minority populations can round to zero.','High','Finite precision saturation is not experimentally complete selectivity.'),
('C05','simulate can output an absolute rate from the same ΔΔG used for selectivity.',GREEN,'A difference fixes a rate ratio, not either absolute activation barrier.','src/commands/simulate.rs; README simulate example','Two barrier pairs(10,11) and(20,21) have same difference but different rates; frozen CLI observation.','INCORRECT','Same ratio 5.4076065654; R rates 290543.5244 versus 0.01358815005 s^-1.','High','The standalone rate function is correct when supplied an actual absolute barrier; the interface is the problem.'),
('C06','Rate and selectivity calculations have a defined finite numerical domain.',GREEN+'; IEEE754 f32 range','Finite input can map outside representable output range; this must be reported.','src/kinetics/eyring.rs; src/commands/simulate.rs','Large positive/negative barriers, temperature extremes, NaN/infinity and zero-temperature inputs.','VERIFIED WITH NUMERICAL LIMIT','Wider grid includes 16 rate underflows and 15 nonfinite rates; CLI checks inputs only.','High','This is a bounded precision/validation claim, not evidence that ordinary barriers have chemically material errors.'),
('C07','MMFF ensemble weights use the normalized Boltzmann equation.',GREEN,'wi∝exp(-(Ei−Emin)/(RT)); kcal/mol; positive temperature; unit degeneracy.','scripts/prepare_data.py::embed_and_optimize','Controlled energy/status injection into frozen routine; independent Decimal weights for single/equal/two/three/offset/extreme/temperature/window cases.','VERIFIED WITH NUMERICAL LIMIT','Maximum population error 1.9429e-16 in isolated weighting tests.','High for arithmetic','Mocked optimizer results do not validate search completeness or MMFF energies as thermodynamic free energies.'),
('C08','Calling the retained MMFF ensemble fully optimized implies that its conformers converged.', 'RDKit installed2026.3.4 MMFFOptimizeMoleculeConfs docstring and official https://www.rdkit.org/docs/source/rdkit.Chem.rdForceFieldHelpers.html','Return status 0 means converged; finite nonzero status may still be unconverged.','scripts/prepare_data.py::embed_and_optimize','Inject status −1/0/1 and nonfinite energies; inspect retained IDs/statuses.','INCORRECT','Status 1 is retained and weighted; negative status and nonfinite energy are excluded.','High','Do not confuse retaining an unconverged state with a proven material descriptor error; magnitude depends on that geometry.'),
('C09','CREST populations correspond to configured QuantumConfig.temperature_k.',CREST+'; '+GREEN,'Population temperature must equal requested T; external table temperature cannot be assumed.','scripts/stericx_quantum.py::crest_ensemble and _conformer_thermodynamics','Frozen realistic two-state summary at 298.15 K, requested 500 K; independently evaluate weights.','INCORRECT','Population error 0.1116127958 at 500 K; command omits --temp and parsed table bypasses recomputation.','High','Direct frozen helper/command audit; no actual external CREST execution is claimed.'),
('C10','CREST missing-table fallback correctly weights supplied electronic energies.',GREEN+'; '+NIST,'Convert Hartree differences to kcal/mol, subtract minimum, normalize atconfigured T.','scripts/stericx_quantum.py::_conformer_thermodynamics','Frozen two-frame energy input at 298.15/500 K, independent Hartree conversion.','VERIFIED WITH NUMERICAL LIMIT','Maximum population error≈1.03e-12, including coordinate-comment energy rounding.','High for tested arithmetic','Degeneracy defaults to one and electronic energies are not state free energies; missing/incorrect degeneracies change expected populations.'),
('C11','Parsed CREST weights are valid nonnegative probabilities.',GREEN,'Each population ≥0; positive finite normalization total.','scripts/stericx_quantum.py::_conformer_thermodynamics','Synthetic malformed population table with weights −0.5,1.5.','INCORRECT','Helper accepts negative population because only finiteness and sum>0 checked.','High','Malformed-table validation test; does not assert real CREST normally emits negative populations.'),
('C12','Native supplied conformer weights correctly average Sterimol descriptors.',GREEN,'Normalize supplied nonnegative weights then Σwi di; Å; preserve ensemble extrema/count.','src/reaction.rs::{conformer_weights,record_from_ensemble}; src/commands/parse.rs','Native frozen CLI on an analytic XYZ pair; independent packed-record decoding.','VERIFIED WITH NUMERICAL LIMIT','Accepted cases max descriptor error 2.6703e-7 Å; 1:3 supplied weights give L=5.2, B1=1.7, B5=4.97.','High for specified cases','Does not establish the supplied weights are thermodynamically justified.'),
('C13','Missing weights with supplied conformer energies produce Boltzmann populations.',GREEN,'Energy-derived populations require an explicit equation and T; uniform averaging follows equal state weights.','src/reaction.rs::conformer_weights','Native parse CSV with unequal energies 0;1 and missing weights.','INCORRECT','Native path uses a uniform average, L=4.7 Å, irrespective of energies; differs from a Boltzmann expectation.','High','Uniform fallback is explicit implementation behavior; documentation must not describe all native averages as energy-derived.'),
('C14','Missing or invalid native conformer geometry does not silently produce a partial ensemble.',GREEN+'; nativeingestionspecifiedsemantics','Reject an incomplete ensemble or explicitly track excluded population; avoid silent partial results.','src/commands/parse.rs','A missing file and a malformed XYZ as the second conformer.','SUPPORTED','Both return errors and no packed record; the native path does not silently discard the bad conformer.','High for cases','Python preparation intentionally filters some failed energies; these are distinct stage semantics.'),
('C15','Buried-volume ensemble weightedmeans implement normalized sums.',GREEN,'Use the same populations for each scalar; treat extrema and conformer-identity reductions separately.','src/geometry/buried_volume.rs::aggregate','One/two/three/nonunit/permuted analytic descriptors versus Decimal.','VERIFIED WITH NUMERICAL LIMIT','Maximum weighted-mean error 6.3578e-7 Å³.','High for finite validatedinputs','Tiny/huge weight normalization and NaN parameters are separate failures; no complete chemical ensemble claim.'),
('C16','Positive finite weights can be normalized independent of common scale.',GREEN,'Multiplying all weightsby any positive finite factor should not change valid probabilities when representable.','src/reaction.rs::conformer_weights; src/geometry/buried_volume.rs::aggregate','Compare weights 1:3 with 1e-10:3e-10; also test sum overflow.','INCORRECT','A valid tiny-weight ratio is rejected as zero total; a large finite sum can overflow.','High','Ordinary normalized weights are unaffected; a correction should rescale before summation.'),
('C17','Public buried-volume aggregation has a scientifically defined result for accepted inputs.', 'Weightedmean mathematicaldomain and publicAPI','Nonfinite components require an error or an explicit missing-data meaning.','src/geometry/buried_volume.rs::aggregate','Direct frozen public API: NaN descriptor with weight 1.','INCORRECT','Returns Ok with NaN vbur_boltz; exact nonfinite output preserved.','High','Direct API finding; normal CLI geometry validation may prevent this input.'),
('C18','Stored conformer energy_span is maximum minus minimum.',GREEN,'Energy span=max(E)−min(E); alternatively require relative energies to have minimum zero.','src/reaction.rs::conformer_energy_span; PackedReactionRecord metadata','Accepted native CSV energies [1,2], independently decode the packed record.','INCORRECT','Stored span is 2 instead of 1; code uses max and does not require minimum zero.','High','When relative energies are correctly referenced to the minimum, max equals max-minus-min.'),
('C19','ee-to-ΔΔG conversion reproduces the standard magnitude equation.',GREEN,'|ΔΔG|=RTln((100+|ee|)/(100−|ee|)); |ee|<100.','scripts/prepare_data.py::ee_to_ddg','Independent equation for validpositive/negative ee and two temperatures.','VERIFIED WITH NUMERICAL LIMIT','Valid interior inputs agree within floating-point precision.','High','Requires kinetic selectivity assumptions; absolute value intentionally discards enantiomer identity.'),
('C20','100% and out-of-range ee can be converted to a finite exact barrier.',GREEN,'100% is an infinite mathematical limit; >100% is invalid; censored measurements require bounds.','scripts/prepare_data.py::ee_to_ddg','Cases ±100/±101 versus the analytic limit/domain.','INCORRECT','All are clipped to 99.999%, giving finite 7.231911... kcal/mol at 298.15 K without censoring metadata.','High','If clipping represents a detection limit, report the assumption and lower bound instead of an exact observation.'),
('C21','Ni-hDA stored targets use their recorded 298.15 K temperature.', 'Corrected primary Ni-hDA SI Table S3; primary author CSV; '+NIST,'Experimental 80 °C, use 353.15 K (allow original rounded R).','data/reactions_raw.csv; scripts/prepare_data.py::normalize_public_sigman; Study 011 temperature description','Independent reverse conversion of all 11 labeled source pairs.','INCORRECT','Ten pairs imply 353.113701 K instead of 298.15 K; maximum room-temperature target difference ≈0.333685 kcal/mol.','High','Do not silently recompute targets; preserve published values and correct provenance separately.'),
('C22','Ni-hDA ID2064 target and ee are mutually consistent.', 'Corrected primary Ni-hDA Table S3 and frozen author CSV','Use the same temperature and selectivity equation for each row.','data/official/ni_hda_kraken.csv row 2064','Independently convert 3% ee at 353.15 K and infer T from the published target.','UNCERTAIN','Source 3% ee and target ≈0.028072 correspond to ≈2% ee at 353 K; implied T=235.37 K.','High confidence in the inconsistency; uncertain which datum is correct','The disagreement exists upstream too; resolution requires author/experimental records.'),
('C23','Population-weighted steric descriptors establish experimental conformer populations.',GREEN,'True equilibrium populations depend on appropriate free energies, state counts, solvent and temperature.','scripts/prepare_data.py; scripts/stericx_quantum.py; README ensembleclaims','Assess energy sources, degeneracy assumptions and failed-conformer handling against statistical thermodynamics.','OUT OF SCOPE','Numerical weights are verified conditionally; no independent experimental population measurements were supplied.','High about scope','MMFF/xTB electronic-energy weighting and finite conformer search remain model assumptions.'),
]
out=['# Conformer and kinetics claim inventory','', 'Numerical evidence and failed cases: [KINETICS_CONFORMERS.md](kinetics/KINETICS_CONFORMERS.md). Each entry is classified separately. These entries include documented behavior and explicitly identified audit propositions. A tested stronger interpretation is not represented as a quotation or a promise that StericX actually makes.','']
basis={
 'C06':'Audit of the accepted numerical domain, not an assertion that documentation promises finite outputs for every finite input.',
 'C08':'Audit of a possible stronger reading of “optimized”; the frozen code retains optimizer status and does not explicitly promise convergence of every retained state.',
 'C13':'Stronger Boltzmann interpretation tested by the audit; the function itself explicitly implements a uniform fallback when weights are absent.',
 'C14':'Validation behavior tested by the audit, not a quoted promise of partial-ensemble renormalization.',
 'C17':'Public-API domain/validation test; no evidence that the ordinary validated CLI supplies NaN descriptors.',
 'C20':'Mathematical interpretation of an implemented clipping behavior; no measured detection limit was supplied.',
 'C23':'Experimental interpretation tested for evidentiary support, not a claim that the README explicitly asserts measured conformer populations.'
}
for ident,claim,source,convention,location,method,status,result,confidence,limits in claims:
    out += [f'## {ident} — {claim}','',f'1. **StericX claim / audited proposition:** {claim} '+basis.get(ident,''),f'2. **Primary/reference source:** {source}',f'3. **Exact convention expected:** {convention}',f'4. **Implementation location:** `{location}`',f'5. **Independent validation method:** {method}',f'6. **Result:** **{status}** — {result}',f'7. **Confidence:** {confidence}',f'8. **Limitations:** {limits}','']
(ROOT/'claims_kinetics.md').write_text('\n'.join(out))
