"""Readable, scope-correct final model inventory from preserved draft claims."""
from models_audit import *


def main():
    legacy = M / 'results/claims_draft_preserved.json'
    if not legacy.exists(): freeze(legacy, (M/'results/claims.json').read_bytes())
    claims = json.loads(legacy.read_text()); by = {c['id']:c for c in claims}
    def change(ident, **kw): by[ident].update(kw)
    # These were audit hypotheses, not quotations or claims made by StericX.
    questions = ['M08','M17','M19','M22','M27','M34','M48']
    for c in claims:
        c['claim_origin'] = 'Audit question; not an attributed StericX quotation.' if c['id'] in questions else 'Paraphrase of documented behavior or implementation contract; see location.'
        c['limitations'] = c['limitations'].replace('floating-point','floating point')
    change('M03', independent_method='Independent NumPy SVD fits on 32 synthetic observations and 10 Ni-hDA observations.', result='Maximum coefficient error 1.164e-7 (native) and 3.032e-8 (synthetic), consistent with stored f32 coefficients. The nominal OLS solve adds a 1e-10 ridge floor.')
    change('M07', result='Independent Ni-hDA Q² = 0.00204170720964314; StericX = 0.002041716065248389.')
    change('M08', claim='Audit question: do fixed-feature diagnostics validate the complete selection workflow?', independent_method='Rerun the frozen CLI with each outer observation withheld; independently refit selection using SVD.', result='The actual CLI fails 7 of 10 outer folds because no descriptor improves the intercept model. No complete CLI outer-LOO Q² exists. An explicitly different reference workflow using training-mean fallback gives Q² = -1.5369635574.', limitations='Current fields explicitly say fixed_feature_loo. The negative result rejects a broader interpretation; the reference fallback is not StericX behavior.')
    change('M11', result='Independent nested-alpha ridge RMSE = 0.732179928258; StericX = 0.732179919787.')
    change('M12', result='Independent nested-alpha LASSO RMSE = 0.800454806613; StericX = 0.800454796181.', limitations='The production solver stops after 2000 cycles without a dual-gap report. Difficult correlated inputs beyond the tested designs remain unverified.')
    change('M13', claim='The regularized nested_loo label fully describes what is nested', result='Alpha choice and scaling are nested. Feature selection is fixed using all outer training labels.', limitations='Interpret this as fixed-feature nested-alpha LOO, not full-pipeline predictive validation.')
    change('M14', expected_convention='BIC = n ln(RSS/n) + p ln(n); the additional forward-step rule requires a decrease greater than 2.', limitations='The improvement cutoff, correlation cutoff 0.95, and n/3 term cap are design choices. Forward search need not find the global BIC minimum.')
    change('M15', source='https://www.statsmodels.org/stable/generated/statsmodels.stats.outliers_influence.variance_inflation_factor.html', expected_convention='VIF_j = 1/(1-R_j²), regressing predictor j on the other selected predictors.', result='Independent inverse-correlation calculation gives 1.002144098 for the synthetic predictors; the native one-predictor case gives 1.', limitations='The denominator is capped below at 1e-9, so singular VIF is represented as 1e9 rather than infinity.')
    change('M16', result='Independent group Q² = 0.001315520959; StericX = 0.001315540471.', limitations='Groups are supplied by the caller; missing labels use row identity. Feature selection still sees all outer labels.')
    change('M17', claim='Audit question: is historical ligand 723 a scaffold-disjoint holdout?', result='Ligand 723 shares a Murcko scaffold with training ligands 1057 and 1058. No exact canonical isomeric SMILES duplicates were found among the eleven records.', limitations='Study 001 calls this a historical holdout; it does not claim scaffold-disjoint validation. Scaffold definition is the recorded RDKit Murcko convention.')
    change('M18', result='Recomputed coefficient percentiles differ by at most 4.44e-16. Stored whole-vector propagation is consistent with the stated paired-row resampling design.', limitations='Replicate fits use ridge 1e-8, compared with a 1e-10 floor for nominal OLS. This checks the procedure and propagation, not small-sample coverage. Selection is fixed and ligand groups are not block-resampled.')
    change('M19', claim='Audit question: does the fixed-feature permutation p-value test the full feature search?', independent_method='2000 paired independent target permutations, with fixed features versus repeated BIC selection.', result='Fixed-feature p = 0.06746626687; repeated-selection p = 0.25137431284.', limitations='Production describes fixed-feature permutations. Independent RNG draws differ from StericX; these are paired diagnostics of conditioning, not an exact RNG replay.')
    change('M20', expected_convention='p = (number at least as extreme + 1)/(B + 1), using training R² and fixed selected columns.', limitations='Counter arithmetic and design are supported by source inspection; the production RNG was not independently proven uniform.')
    change('M21', claim='The 95% Student-t multiplier is numerically accurate on the audited degrees of freedom', expected_convention='Inverse two-sided tail at alpha = 0.05 and positive residual degrees of freedom.', independent_method='SciPy t.isf for df = 1, 2, 3, 8, 29, 100 and 1e6.', result='Maximum absolute 95% quantile error = 1.720721343e-10.')
    change('M22', claim='Audit question: does the public Student-t inverse handle all accepted tail inputs?', expected_convention='Return the finite quantile for positive df and 0 < alpha < 1, or explicitly report a numerical limit.', independent_method='SciPy t.isf and the analytic Cauchy tail, with alpha = 1e-8 and df = 1.', result='StericX returns 1048576; the reference is 63661977.23675813 (98.35% relative error).', limitations='The silently capped bracket does not affect the fixed 95% intervals at the audited positive integer degrees of freedom.')
    change('M23', result='Synthetic screening prediction-interval endpoint error <= 5.33e-15.', limitations='Conditional on a fixed correct linear mean and IID homoscedastic normal errors. Does not include descriptor, selection, mechanism, or laboratory-shift uncertainty.')
    change('M24', independent_method='Independent design inverse and SciPy critical values on training, interpolation and extrapolation points.', result='Confidence intervals use sqrt(h), whereas prediction intervals use sqrt(1+h); observed values match.')
    change('M25', claim='Screening distinguishes bootstrap mean-response uncertainty from a prediction interval', expected_convention='Joint coefficient-replicate propagation estimates fitted-mean uncertainty; a future observation also has residual scatter.', independent_method='Recompute replicate predictions and their empirical 2.5% and 97.5% quantiles.', result='The method is correctly named percentile_bootstrap_mean_response. Endpoint differences <= 1.11e-16 on the tested library.', status='VERIFIED WITH NUMERICAL LIMIT', limitations='The current README explicitly distinguishes these intervals. Neither bootstrap coverage nor uncertainty from selection or chemical shift is established.')
    change('M26', expected_convention='Marginal 95% coefficient intervals do not generally form a joint 95% confidence region.', independent_method='Create 1000 joint coefficient replicates with disjoint 2.4% positive and negative tails.', result='The marginal band collapses to one value and covers 90.4% of joint predictions; the joint 95% interval spans approximately 200 response units.', limitations='A mathematical serialized-model counterexample disproves a universal guarantee. It is not a measured chemistry error rate.')
    change('M27', claim='Audit question: are nominal 95% intervals calibrated on the available Ni-hDA ranking panels?', expected_convention='Approximately 95% coverage over the stated prediction population, subject to model assumptions.', independent_method='Recalculate coverage from every frozen Study 011 prediction and target.', result='92/141 = 65.248% coverage; interpolation subset 70/108 = 64.815%.', limitations='Overlapping panels reuse eleven ligands. These are descriptive coverage fractions, not 141 independent trials. Aggregation mismatch complicates causal attribution.')
    change('M28', expected_convention='z_j = (x_j - training mean_j)/training SD_j.', independent_method='Known anisotropic coordinates and independent affine transformation.', result='Training, nearby and extreme points match, subject to the f32 input representation.')
    change('M29', expected_convention='Minimum Euclidean distance to any standardized training point.', independent_method='SciPy cdist versus the public API observer and frozen screening CLI.', result='CLI distance error is zero on the tested library; an exact training point has distance zero.')
    change('M30', expected_convention='Use each training point’s nearest other point, then max, mean + SD or mean + 2 SD as the chosen threshold.', independent_method='Inspect calibration formulas and recompute training nearest-neighbor distances independently.', result='The default maximum threshold matches independent distances; alternate formulas match their declared algebra.', limitations='These are policies, not calibrated probabilities. Duplicates can make the threshold zero; an isolated training point can widen the maximum rule.')
    change('M31', expected_convention='Flag values below a selected-feature minimum or above its maximum; equality is inside.', independent_method='Synthetic boundary, in-range and extreme inputs, including a point outside the convex hull but inside every range.', result='Range flags behave as declared. A bounding-box interior point outside the convex hull is still labeled interpolation.', limitations='A feature box and nearest-neighbor rule do not define chemical applicability or the training convex hull.')
    change('M32', expected_convention='h = xᵀ(XᵀX)^(-1)x, with intercept and the recorded training standardization.', independent_method='NumPy inverse and SVD on known and fitted design matrices.', result='CLI leverage error <= 7.91e-14 in the tested library.', limitations='The fit’s small ridge floor perturbs the unregularized equation. Leverage alone does not calibrate prediction error.')
    change('M33', expected_convention='Mahalanobis distance = sqrt((n-1)(h-1/n)) for an ordinary full-rank linear design with intercept.', independent_method='Independent sample-covariance inverse on known two-dimensional geometry.', result='CLI error <= 1.43e-13 on the nonsingular test library.', limitations='The identity requires full rank and the correct covariance convention.')
    change('M34', claim='Audit question: does the public stored-geometry API identify singular covariance before reporting Mahalanobis distance?', expected_convention='Ordinary Mahalanobis distance needs an invertible covariance; a regularized surrogate should be identified.', independent_method='Inject a rank-one covariance stabilized with the same 1e-10 slope floor into TrainingGeometry.', result='Reports 316227.75293364684 and no unavailability reason for an off-manifold query.', limitations='This is an accepted serialized-geometry/API witness. Native forward selection did not generate this specific singular fitted model.')
    change('M35', claim='The emitted trust label reliable denotes calibrated chemical reliability', expected_convention='Reliable prediction would require held-out calibration beyond a descriptor range and nearest-neighbor rule.', independent_method='Trace the label decision and independently recalculate Study 011 errors by domain.', result='Interpolation MAE = 0.9332371 kcal/mol with 64.815% nominal 95% interval coverage.', limitations='README already states that descriptor distance is not calibrated reliability; the emitted label is stronger than the evidence.')
    rank = {'M36':('Ascending objective ranking','Increasing predicted response'), 'M37':('Descending objective ranking','Decreasing predicted response'), 'M38':('Magnitude objective preserves negative predictions','Decreasing absolute predicted response while retaining the original sign'), 'M39':('Prediction ties use the declared deterministic order','Resolve ties by identifier, then original position')}
    for ident,(claim,expected) in rank.items():
        change(ident,claim=claim,expected_convention=expected,independent_method='Compare independent sorts with frozen synthetic-library outputs and metadata variants.',result='Observed ranking matches the declared objective.',limitations='Ranking arithmetic does not validate the chemical predictions.')
    change('M40', expected_convention='Exclude and explain candidates missing a descriptor used by the selected model.', independent_method='A frozen CSV includes one row without required Sterimol L.', result='The row is excluded with sterimol_l recorded as missing; the other nine candidates remain.')
    change('M41', expected_convention='Exclude matching stable identifiers and report identifiers that were not found.', independent_method='An exclusion CSV contains high twice and not_present once.', result='The matching candidate is excluded; the unresolved identifier is reported.', limitations='Identifier matching is not chemical-identity matching.')
    change('M42', expected_convention='Diversity changes selection or ordering, while preserving predictions; weight zero recovers ordinary ranking.', independent_method='Compare per-identifier predictions for default, diversity weight 0.65 and weight 0.', result='Maximum prediction change is zero; weight-zero ordering matches ordinary ranking.')
    change('M43', expected_convention='Include OOD candidates by default; an explicit domain-only filter records removals.', independent_method='Extreme descriptor candidates and the in-domain-only flag.', result='Default output retains extrapolations; the requested filter leaves a traceable exclusion record.', limitations='A warning does not establish model reliability.')
    change('M44', expected_convention='The official ten training IDs and vbur_max_delta_qvbur_min, with univariate OLS.', independent_method='Fresh primary CSV and official notebook; independent SVD and fixed-feature LOO.', result='Slope = 0.0892042662475, intercept = -0.197934470338; R² = 0.8193060694 and conditional Q² = 0.7521012497.', limitations='The original search considered 191 descriptors on the same ten labels. Ligand 723 is historical, not prospective, and ID2064 has conflicting primary ee/target values (M67).')
    change('M45', claim='The native compact-feature ablation has weak conditional Ni-hDA validation', expected_convention='Reproduce the declared native fit without substituting the published buried-volume predictor.', independent_method='Frozen CLI fits, independent SVD diagnostics and full outer-selection CLI attempts.', result='Native fixed-feature Q² = 0.002041716; seven of ten full-selection outer folds fail to fit.', status='VERIFIED WITH NUMERICAL LIMIT', limitations='Study 001 already reports this negative ablation. The mean-fallback reference Q² is not a completed StericX pipeline score.')
    for ident,study in [('M46','002'),('M47','003')]:
        change(ident,expected_convention='The same ten training IDs and the study’s declared per-ligand buried-volume predictor.',independent_method='Independent SVD refits from frozen per-ligand inputs, with every fitted and LOO value saved.',result='Training, fixed-feature LOO and historical ligand-723 predictions reproduce within saved CSV precision.',limitations='This verifies model arithmetic, not the independently audited geometry-generation process or new experimental performance.')
    change('M48',claim='Audit question: has the prospective deck established experimental predictive validity?',expected_convention='New measured outcomes obtained after predictions were fixed, without refitting.',independent_method='Inspect the frozen protocol, prediction deck and available measurement status.',result='No prospective experimental outcome dataset was available for this audit.',limitations='The separate kinetics audit identifies a target-temperature mismatch; computational reproduction cannot supply missing experiments.')
    change('M49',expected_convention='Retain all 57 planned panels, including ten failures, and the locked failure penalties.',independent_method='Recompute 141 prediction rows, 47 successful panels, and all-57 summary denominators.',result='Top-1 = 0.1578947 versus random 1/3; top-2 set overlap = 0.4649123 versus random 2/3; mean successful-panel Spearman rho = -0.3404255.',limitations='Panels overlap; these are not 57 independent chemistry experiments.')
    change('M50',expected_convention='Candidate and training predictors must use the same descriptor and conformer-aggregation definitions.',independent_method='Trace geometry input paths and independently recalculate frozen Study 011 prediction differences.',result='Largest screen-versus-fit disagreement = 1.20976108497 kcal/mol; representative geometry versus weighted ensemble is the documented mismatch.',limitations='The README and Study 011 disclose it. A correctly constructed precomputed descriptor CSV can avoid this specific mismatch.')
    fits=json.loads((M/'results/crosscoupling_reference_models.json').read_text())
    for i,rx in enumerate(['I','II','III','IV','V','RS1','VII','VIII','IX','X','XI','XII'],51):
        native=next(x for x in fits if x['reaction']==rx and x['descriptor']=='current_stericx_fullprecision' and x['label_convention']=='official_ge')
        reference=next(x for x in fits if x['reaction']==rx and x['descriptor']=='public_kraken_fullprecision' and x['label_convention']=='official_ge')
        n=native['reference'];r=reference['reference']
        change(f'M{i}', expected_convention='Use the primary active convention yield >= cutoff, declared class weights and a depth-one weighted-Gini classifier.',independent_method='Complete primary SI extraction; independent exhaustive cutpoint search versus sklearn, on reference and fresh StericX descriptors.',result=f"N={native['n']}; current threshold {n['threshold']:.12g} ({n['direction']}), MCC {n['mcc']:.12g}; reference-descriptor threshold {r['threshold']:.12g} ({r['direction']}), MCC {r['mcc']:.12g}. All per-row reference/sklearn predictions agree.",status='UNCERTAIN' if rx in ['II','IV','RS1','VII','VIII','IX'] else 'SUPPORTED',confidence='high for arithmetic; limited for exact published reproduction',limitations='The complete open preprint SI is primary evidence; final Science SI retrieval returned 403. Printed yields and source versions do not exactly reproduce every published summary metric. All twelve model fits are resubstitution, not unseen-ligand validation.')
    change('M63',expected_convention='Official notebook: inactive if yield < cutoff, otherwise active (>=).',independent_method='Extract and preserve every primary-table row exactly at a cutoff.',result='Study scripts use strict >. Seven row labels differ across I, II, IV, V, VII and VIII.',limitations='Published rounded yields can also differ from original unrounded measurements; that is separate from the definite code-inequality mismatch.')
    change('M64',claim='The cross-coupling bootstrap intervals describe apparent-fit variability',expected_convention='Fitting and scoring the same resample evaluates apparent fit, not held-out prediction.',independent_method='Inspect the resampling unit and scoring set in both frozen study scripts.',result='Each bootstrap sample is used for fitting and scoring. The reported intervals do not establish unseen-reaction or unseen-ligand calibration.',status='SUPPORTED',limitations='The interval may summarize resampled in-sample fit; no external predictive coverage follows from it.')
    def add(ident,claim,source,convention,location,method,result,status,limits):
        claims.append(dict(id=ident,claim=claim,claim_origin='Explicit study claim or audit question as stated.',source=source,expected_convention=convention,implementation=location,independent_method=method,result=result,status=status,confidence='high within the stated scope',limitations=limits))
    add('M65','Study 007 withholds the reaction in its leave-one-reaction-out test',by['M08']['source'],'No target from the held reaction may enter its fit. Ligand identity overlap must be reported separately.','studies/study_007_crosscoupling.py:333','Independent six-fold threshold fits and ID-set intersections.','Reaction targets are withheld. All 89 test ligands recur in training for five folds; 20/34 recur for reaction I.','VERIFIED WITH NUMERICAL LIMIT','This is reaction-level transfer among known ligand families, not scaffold-disjoint or generally unseen-ligand prediction.')
    add('M66','The Boltzmann descriptor is a scientifically justified reference for Study 007’s single-geometry comparison','Statistical-mechanical ensemble definition; see kinetics/conformer audit.','Justify the comparison target from the geometry and ensemble populations; mathematical equality is not required for a sensitivity comparison.','docs/study_007/STUDY_007.md:59','Inspect the actual fair-reference wording and reported imperfect agreement; distinguish that methodology from a hypothetical exact-equivalence claim.','The study calls the Boltzmann descriptor the fair published reference and reports R² = 0.9735 and MAE = 0.446 percentage points. It does not assert mathematical equality. This audit has not independently established whether that reference choice is appropriate for all eighteen cases.','UNCERTAIN','No new eighteen-geometry comparison was run here. A separate audit hypothesis of universal single-geometry/ensemble equality is mathematically false, but is not a claim attributed to Study 007.')
    claims[-1]['confidence']='high for source attribution; limited for methodological suitability'
    add('M67','The retained Ni-hDA target and ee columns are mutually consistent', 'https://acs.figshare.com/articles/journal_contribution/30933433','At 353.15 K, absolute DDG = RT ln((100+ee)/(100-ee)).','data/reactions_raw.csv; primary reaction_data.csv; corrected SI Table S3','Inspect rendered corrected SI page S22; independently convert every retained ee.','ID2064 has ee=3% but target0.028072105, corresponding to approximately2%; independent3% conversion gives0.0421195099234 kcal/mol.','UNCERTAIN','The primary sources conflict internally. Do not change StericX targets until authors or original measurements establish the intended value.')
    add('M68','The corrected Ni-hDA SI retains the model’s eleven ligand IDs and printed DDG targets','https://acs.figshare.com/articles/journal_contribution/30933433','Compare the actual corrected table, without assuming the correction changes or validates every value.','models/sources/correction_si.pdf, Table S3, page S22','Row-by-row checked transcription against the primary CSV.','The retained IDs and printed DDG column match; ee-to-DDG inconsistency remains for2064.','SUPPORTED','The correction letter was inaccessible (403). Only the table and relevant modeling section were reviewed; no chromatogram reassessment or full correction scope is claimed.')
    add('M69','Frozen evaluation rejects predictions inconsistent with the supplied finite model','Declared integrity contract in src/model/evaluation.rs module documentation.','Reject nonfinite predictions before comparing them to a finite model response or reporting accuracy.','src/model/evaluation.rs:81; src/commands/evaluate.rs:51','Frozen CLI evaluation of three copied prediction CSVs: NaN, infinity and a finite mismatch.','NaN is accepted with exit 0; MAE and RMSE become NaN in stdout and null in JSON. Infinity and the finite mismatch are rejected with exit 2.','INCORRECT','A concrete CLI validation failure. The single-row R² being unavailable is expected independently and is not itself the failure.')
    add('M70','Study 007’s formula guard rejects isomeric geometries before comparison','Distinct explicit molecular graphs and independent RDKit CalcMolFormula; source claim in Study 007 section 4.','Chemical identity requires connectivity and, when relevant, stereochemistry; equal element counts alone do not distinguish constitutional isomers.','docs/study_007/STUDY_007.md:57; studies/study_007_crosscoupling.py:503–507','Freeze explicit CCCP and CCPC graphs, XYZ and SDF files; independently verify C3H9P and different P neighbor sets; execute the frozen formula helper definitions.','Primary n-propylphosphine and secondary methylethylphosphine both return ((C,3),(H,9),(P,1)). The cross-isomer pairing passes the formula guard, despite one versus two heavy neighbors at phosphorus.','INCORRECT','Synthetic helper-level falsification of the universal guard claim only. No claim that any of the eighteen historical geometry mappings was actually wrong; other lookup and presence conditions were not rerun.')
    # Specific additional qualifiers prevent a design-policy test from sounding
    # like broad chemical validation. No result is upgraded because tests pass.
    for c in claims:
        for key in ['claim','expected_convention','independent_method','result','limitations']:
            c[key]=c[key].replace('ID2064','ID 2064').replace('target0.','target 0.').replace('approximately2%','approximately 2%').replace('independent3%','independent 3%').replace('for2064','for 2064').replace('gives0.','gives 0.').replace('Study002','Study 002').replace('Study003','Study 003').replace('Study011','Study 011')
    save(M/'results/claims.json',claims)
    out=['# Model, statistics and screening claim inventory','','Claims are paraphrases of the cited implementation or documentation. Rows explicitly marked **audit question** test a possible interpretation; they are not quotations attributed to StericX. Each status applies only to the written scope. See `models/REPORT.md`, `models/DISCREPANCIES.md`, and full-precision per-row results.','','| ID / claim or audit question | Primary/reference source | Exact convention | Implementation | Independent method | Result / status | Confidence | Limitations |','|---|---|---|---|---|---|---|---|']
    for c in claims:
        vals=[c['id']+' — '+c['claim'],c['source'],c['expected_convention'],c['implementation'],c['independent_method'],c['status']+': '+c['result'],c['confidence'],c['limitations']]
        out.append('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in vals)+' |')
    (A/'claims_models.md').write_text('\n'.join(out)+'\n')


if __name__=='__main__': main()
