#!/usr/bin/env python3
"""Render final audit narrative from frozen metrics; no scientific code changes."""
import datetime,json
from pathlib import Path
from kraken_analyze import ROOT,sha,save
m=json.loads((ROOT/'analysis/metrics.json').read_text());d=json.loads((ROOT/'interpretation/direct_morfeus_metrics.json').read_text());a=json.loads((ROOT/'interpretation/same_center_analytic_metrics.json').read_text());h=json.loads((ROOT/'interpretation/headline_outlier_dossiers.json').read_text())
lines=['# Independent Kraken reproduction audit','', 'Audited system: commit `6393aafe0d983e504baf8abc1e18dc2a0f0d40e7`. Production scientific code was not changed. Raw native outputs were frozen before independent comparison. This is an audit of numerical definitions and reproduction, not experimental validation.','',
'## Main findings','',
'Fresh acquisition covers all 1,566 IDs in the historical comparison universe: 1,546 have 31,721 available DFT conformers; 20 have no available DFT geometries. The audit attempted every available conformer, including cases excluded by the historical geometric prefilter. Complete native ensembles exist for 1,543 buried-volume ligands, 1,544 coordination-Sterimol ligands and all 1,546 pyramidalization ligands. No numerical outlier was removed. Eight conformers produce false fourth-neighbor inferences relative to independently reconstructed SDF topology; another valid symmetric molecule produces a buried-volume error. These failures are retained separately, never replaced with partial-ensemble minima.','',
'The headline minimum of maximum adjacent-quadrant differences reproduces the approximate historical aggregate score: N=1,543, MAE=0.270886692 Å³, RMSE=0.490777865 Å³, one-to-one R²=0.985128630, maximum error=4.559474133 Å³. This does not establish exact convention equivalence. Every one of the twenty largest headline discrepancies becomes ≤0.006275429 Å³ against the published values when independently evaluated with the original Kraken center and density. The original DFT center is a normalized sum of **raw bond displacement vectors**, not an electronic localized-orbital center. StericX normalizes each bond vector before summing. Tertiary donors also differ; the two centers do not generally coincide.','',
'Sterimol comparisons additionally differ because original Kraken substitutes H radius1.09 Å while StericX uses1.20 Å, and the angular scans differ. Removing those convention differences does not eliminate every implementation discrepancy: all-corpus same-center/same-radii closed-form projections reveal native L error0.0036931285331647246 Å and B5 error0.004176904379527002 Å in near-axis real conformers. The analytic formulas avoid the approximate quaternion rotation branch.','',
'Pyramidalization on identical exported geometries agrees closely with independent contemporary Morfeus over all 31,721 conformers: maximum |ΔP| = 3.2010947048632943e−7 and |Δalpha| = 4.8856123654239525e−5 degrees. Yet the published ligand extrema differ by up to0.007218747 in P and1.155986692 degrees in alpha. Independent Morfeus reproduces those large discrepancies too. Therefore they cannot honestly be attributed solely to Rust f32 rounding; historical geometry/ensemble/reference provenance remains unresolved.','',
'## Sources and exact conventions','',
'- Gensch et al., JACS144,1205–1217 (2022), [10.1021/jacs.1c09718](https://doi.org/10.1021/jacs.1c09718), original [SI PDF](https://acs.figshare.com/articles/journal_contribution/Supplementary_material_for_A_Comprehensive_Discovery_Platform_for_Organophosphorus_Ligands_for_Catalysis_/18307112) and [SI archive](https://acs.figshare.com/articles/journal_contribution/Supplementary_material_for_A_Comprehensive_Discovery_Platform_for_Organophosphorus_Ligands_for_Catalysis_/18307121). Exact downloaded bytes, source URLs/status/timestamps/headers and hashes are in `raw_sources/`. PDF pages8,10,12 are rendered there for equation/convention inspection.',
'- Original [DFT implementation at immutable commit 4eaad505c1343e6083032b4a3fda47e004e19734](https://github.com/the-matter-lab/kraken/blob/4eaad505c1343e6083032b4a3fda47e004e19734/conf_selection_and_DFT/PL_dft_library_201027.py), functions `get_conmat`, `add_valence`, `morfeus_properties`, `read_ligand`. This is evidence of the reference implementation, not physical truth.',
'- Fresh [MolSSI Kraken API](https://descriptor-libraries.molssi.org/api/kraken/docs) molecule metadata, published DFT descriptors and SDF conformer exports. Each response is frozen with provenance; failed responses remain preserved.',
'- Morfeus0.8.0, frozen installed source and package versions in the master initial manifest. Contemporary Morfeus is an independent implementation; it is not claimed to be the exact2021 dependency version.','',
'| Convention | Original Kraken DFT | Frozen StericX measurement |','|---|---|---|',
'| Donor/geometry | First eligible trivalent P by primary connectivity; original graph rule frozen | Same mapped P chosen from independent SDF topology; SUT separately infers its neighbors |',
'| Virtual center | P +2.28 normalize(Σ(P−neighbor)) | P +2.28 normalize(Σ normalize(P−neighbor)) |',
'| Vbur | Sphere3.5 Å; Bondi×1.17; H excluded; density0.001 | Same sphere/radii/H; native default density0.01 |',
'| Frame | Three substituent planes; original neighbor order; extrema across orientations | Reference first then detected neighbors; extrema across orientations |',
'| Total/near/far | Last orientation retained | First orientation retained |',
'| Sterimol | Dummy Pd→P; Bondi except1.20→1.09; 3,600 directions; L +0.40 Å | Dummy→P; H1.20; 360 directions; L +0.40 Å |',
'| Pyramidalization | Three nearest neighbors excluding dummy Pd; P dimensionless, alpha degrees | Explicit SDF-bonded three neighbors in observation adapter; automatic donor/frame audit is reported separately |',
'| Ensemble | min/max/delta and descriptor at minimum-Vbur conformer; Boltzmann reduction uses source free energies | Exact full available ensembles for four unweighted reductions; source weights unavailable |','',
'SDF connectivity was reconstructed by the API export tool (Open Babel), so it is independent of StericX but still an inference, not an experimental bond determination. Original Kraken and SDF neighbors agree in the diagnostic records; current automatic StericX connectivity can disagree. The export coordinates have four decimal places. Index mapping is unchanged; dummy Pd is appended only in independent calculations and excluded from occupancy.','',
'## Freeze, reproducibility and coverage','',
'`primary/acquisition_plan.json`, `primary/ligands_manifest.json`, `primary/conformers_manifest.json`, `prepared_all/manifest.json`, `sut/manifest_frozen.json`, `morfeus_outliers/selection_frozen.json`, `morfeus_outliers/manifest_frozen.json`, `full_analytic_reference/manifest_frozen.json` and `interpretation/manifest.json` form the phase manifest chain. Native values include exact observed f32 values and IEEE bit patterns. Reference calculations retain full available Python float precision.','',
'`analysis/comparisons.csv` contains molecule-by-molecule results for56 descriptor/reduction combinations; `analysis/conformers.csv` contains every native conformer result. Complete property ensembles are required. `analysis/excluded_comparisons.json` lists every unavailable input or failed property; `analysis/operation_errors.json` contains all17 operation errors on9 conformers. `analysis/top20_by_descriptor.json` retains20 worst entries for every reported metric. `delta_interpretation/all_top20_outlier_dossiers.json` joins each entry to independent diagnostics, exact input IDs and the scope/limitations of the causal interpretation.','',
'The published SI workbook contains1,558 rows; the newer Ni-hDA comparison table contains1,566. The extra IDs are724,1057,1058,2059,2062,2063,2064,2067. Across190 shared numeric columns the largest SI/API-table difference is1.000000082740371e−8. `primary_si/` preserves exact XML-cell extraction and every difference. The corpus expansion and independently retained failures explain why this audit reports different coverage from the historical1,541/31,611 headline; it did not select IDs to force that count.','',
'Reproduction scripts are under `scripts/`. Run acquisition/preparation/native observation before reference interpretation in a fresh audit destination; raw phase directories intentionally refuse overwriting. `kraken_run_sut.py` observes the frozen production implementation through the audited adapter. `kraken_morfeus_outliers.py` performs the untuned convention matrix; `kraken_full_analytic_reference.py` evaluates all 31,721 conformers; `kraken_interpret.py` performs independent dot-product L/B5 projections and statistics. Source/method changes require a new phase directory. The master reproducibility procedure documents complete commands and environment.','',
'## Full numerical comparison','',
'Each row below uses published values as x and native values as y. R² is **1−Σ(y−x)²/Σ(x−mean(x))²**, not squared correlation. Slope and intercept are diagnostic OLS y~x only; they are never applied to correct native descriptors. `analysis/metrics.json` preserves full precision. Absolute BV fields use Å³; Sterimol uses Å; P is dimensionless; alpha uses degrees; percent Vbur uses percentage points.','',
'| Descriptor/reduction | N | MAE | RMSE | Max | Median | R² | Slope | Intercept |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
for k,v in sorted(m.items()):lines.append('| '+k+' | '+str(v['N'])+' | '+' | '.join(f"{v[f]:.9g}" for f in ['MAE','RMSE','maximum_absolute_error','median_absolute_error','R2_one_to_one','slope','intercept'])+' |')
lines += ['', 'Residual figures: [buried-volume minima](analysis/buried_volume_min_residuals.png), [Sterimol extrema](analysis/sterimol_extrema_residuals.png), [pyramidalization extrema](analysis/pyramidalization_extrema_residuals.png). The Sterimol plots show the systematic positive radius-convention shift clearly; a large R² does not remove that bias.','',
'## Direct Morfeus and convention isolation','',
'The590-record selection was frozen before calculating the reference variants. It includes all conformers of the20 largest headline outliers, every available SUT extremizer for all per-descriptor top20 min/max/vburminconf entries, and every native operation failure. This is a deliberately adverse diagnostic selection, not a random estimate of overall error. Native-success denominators differ because errors are retained, not imputed.','',
'An initial matched-radii adapter accidentally omitted explicit1.17 scaling because Morfeus does not rescale supplied radii. That failed campaign is preserved in `morfeus_outliers_attempt1/INVALID_MATCHED_VARIANT.json`; it is **not scientific evidence against StericX**. The corrected campaign explicitly scales the supplied radii and was rerun before interpretation. An initial analysis inventory parser also failed before comparisons; its failure record is preserved in `interpretation_attempt1/`.','',
'With center, radii, coordinates, density and first-orientation convention matched, direct Morfeus total BV differs by at most 1.095939546758018e−5Å³ over 581 native-success cases. The corresponding maximum percent Vbur difference is8.34638332491977e−6 percentage points, including native percent rounding (`interpretation/matched_default_percent.json`). Quadrant/octant extrema contain one grid-cell discrepancy: max0.011656810711858867Å³ in adjacent-quadrant difference. Thus the total-volume kernel shows strong agreement on those cases while finite boundary/frame arithmetic remains measurable. Matching default density is essential: changing only the independent density to0.001 gives total BV difference up to0.45010229210903674Å³. That is convergence sensitivity, not an exactness failure by itself.','',
'For identical coordinates/center/radii, Morfeus B1 differs by up to0.044101899989216875Å on582 diagnostic cases. Its3,600-direction scan and the native360-direction scan do not define identical numerical approximations. L/B5 maxima on that subset are0.0017224155361290627/0.002769704392543204Å. The independent all-corpus closed-form campaign broadens the observation to31,713 valid native axes and finds larger deviations:','',
'| Descriptor | Max error Å | Native | Independent | Exact case |','|---|---:|---:|---:|---|']
for name,v in a.items():
 c=v['maximum_case'];lines.append(f"| {name} | {v['maximum_absolute_error']:.17g} | {c['sut']:.17g} | {c['reference']:.17g} | {c['id']} |")
lines += ['', 'The formulas are L=max_i[(x_i−c)·u+r_i]+0.40 and B5=max_i[||(x_i−c)−((x_i−c)·u)u||+r_i], whereu=(x_P−c)/||x_P−c||. They require no quaternion and do not call a scientific StericX kernel. Frozen coordinates, radii and center are used verbatim, promoted to float64. Most errors are much smaller (median about4–5e−7Å), but the near-parallel/antiparallel rotation approximation in `glam::Quat::from_rotation_arc` is an implementation limitation that a mean would conceal. See `focused_diagnosis/axis_counterexamples.json` for direct Morfeus corroboration and complete failing inputs.','',
'## Twenty largest headline discrepancies','',
'All20 complete ensembles were independently recalculated under both centers and both densities. The table gives the original published reference, native default result and untuned primary-convention Morfeus result. Every input, donor, neighbor list, exact center, four variant values and proposed correction is retained in `interpretation/headline_outlier_dossiers.json`.','',
'| Kraken ID | P–H count | Published Å³ | Native Å³ | Error Å³ | Primary Morfeus Å³ | Remaining error Å³ |','|---|---:|---:|---:|---:|---:|---:|']
for v in h:
 p=v['reference_variants']['primary_0001'];lines.append(f"| {v['molecule_id']} | {v['P_H_count']} | {v['reference']:.10g} | {v['sut']:.10g} | {v['residual']:.10g} | {p['value']:.10g} | {p['residual_vs_published']:.10g} |")
lines += ['', 'Many of the largest cases contain no donor-bound hydrogens. For example ID1796 has center directions separated by about9.715–9.718degrees and native headline error−4.559474133Å³; the primary convention gives19.707981404Å³ versus published19.712165020Å³. Raw-versus-unit bond weighting also matters for heterogeneous substituent lengths and elements in tertiary donors. Labeling all such differences as an electronic P–H LMO effect is contradicted by the original DFT code and these calculations.','',
'## Remaining published-value outliers','',
'Primary-convention contemporary Morfeus was run on every available conformer for all three Sterimol values and both pyramidalization values. It substantially reduces overall Sterimol error, but residual outliers persist: L max for ID1290 differs0.9550323238Å, B5 min for ID1805 differs0.6492286866Å, B1 max for ID560 differs0.2742709684Å. Pyramidalizationalpha max for ID1290 differs1.156001260degrees. These are independent disagreements with the published aggregate using currently exported geometries. They are not evidence that native code alone caused the published mismatch.','',
'`interpretation/primary_ensemble_vs_published.csv` and `primary_ensemble_metrics.json` retain every complete reference ensemble without trimming. Independent nearest-neighbor and SDF-neighbor pyramidalization agree throughout this corpus; native differences on the same geometries are orders of magnitude below the largest published discrepancy. `focused_diagnosis/pyramidalization_coordinate_rounding.json` examines all4,096 corners of the donor/three-neighbor ±0.00005Å rounding box in major outlier geometries. Across 251 conformers and 1,028,096 corner evaluations, the largest alpha deviation is 0.0103514124 degrees; for ID1290 it is at most 0.0089272857 degrees, far below its 1.156-degree published discrepancy. It is a sensitivity experiment, not a rigorous global bound over the box. A separate conservative determinant bound (`focused_diagnosis/pyramidalization_rounding_bound.json`) covers arbitrary continuous coordinate perturbations in that box. All 251 cases have positive-alpha branch and noncollinearity margins. The bound is at most0.000623445508668 in P, including both ID1290 conformers, so its0.007218735 published P discrepancy cannot arise from ordinary4-decimal rounding alone if ensemble and atom identity are unchanged. The defensible unresolved explanations include exported-versus-original geometry/ensemble provenance and historical reference dependency behavior. Raw Gaussian logs, original full-precision conformer coordinates, per-conformer computed properties and exact historical dependency versions are needed to choose among them. Neither dataset is declared wrong solely because they disagree.','',
'## Failures and chemical eligibility','',
'Ligand1281 conformers54235/54241 and ligand1907 conformers63291–63296 receive a fourth geometrically close neighbor in StericX; independent SDF topology and original primary connectivity have three. Eight BV and eight coordination-Sterimol errors are preserved. Atom identity, donor distances, radius thresholds, independent neighbor lists and outputs are in `focused_diagnosis/operation_failure_dossiers.json`. The historical prefilter mirrored the same native cutoff, so removing those cases before validation would conceal this failure mode. Explicit topology is preferable when trustworthy; a distance cutoff alone cannot establish chemical bonding.','',
'Ligand1299 conformer54318 has three bonded substituents and yields a valid symmetric zero adjacent-quadrant difference in an independent calculation. NativeBV rejects it as a degenerate frame. Zero anisotropy is not by itself chemically impossible or mathematically undefined. The exact molecule and all failed/reference records are retained; no algorithm was changed.','',
'## Boltzmann data availability and limits','',
'Full-library Boltzmann reductions cannot be independently reconstructed from the acquired historical inputs. This is an evidence limitation, not a successful reproduction. `energy_source_search/REPORT.md` records checks of both current/v2 API schemas and endpoints, five diverse conformers, alternate exports, the original immutable repository and releases, the complete SI archive contents, and the updated Sigman repository. API conformer records contain `data:null`; neither geometry export nor the official SI tables supply source per-conformer free energies/weights. The updated repository contains33 regenerated validation ensembles, which cannot be substituted for historical source weights. Published aggregate Boltzmann descriptors are outcomes, not legitimate inputs for reproducing themselves.','',
'## Classification and proposed follow-up','',
'- **Supported approximate reproduction:** the headline published-reference score and the listed subset of geometric families, with all errors and missing inputs quantified.',
'- **Verified with numerical limits on tested geometry:** direct same-convention BV kernel agreement (including measured cell-boundary differences) and native pyramidalization versus Morfeus over the full exported corpus.',
'- **Incorrect claims:** electronic-LMO explanation of original Kraken DFT center; assertion that raw and normalized bond sums generally coincide for tertiary phosphines; exact axis rotation for all native L/B5 cases; blanket chemical validity of current geometric donor-neighbor inference; rejection of all symmetric zero-anisotropy cases as invalid.',
'- **Terminology issue:** saying the “entire vbur family” was validated when only eight absolute geometric fields and selected ensemble reductions were tested. Distal/total molecular volumes, ratios and source-energy Boltzmann reductions remain outside that numerical claim.',
'- **Uncertain:** why a minority of published extrema disagree with both native and independent calculations on currently exported geometries; exact historical per-conformer thermochemistry; predictive/experimental usefulness of these descriptor agreements.','',
'First correct the documentation and qualify convention-specific claims. A later scientific code change could address the demonstrated axis approximation, false bonded neighbors and symmetric-zero rejection only after its desired convention is explicit and separately reviewed. Reproducing original Kraken values requires deciding whether to adopt its center/radius/density conventions; that is a descriptor-definition choice, not a harmless performance fix. Obtain original calculation records to resolve remaining published-value provenance. Do not remove disagreeing molecules or infer experimental generalization from descriptor parity.','']
from kraken_prose import polish
text=polish('\n'.join(lines))
if (ROOT/'delta_interpretation/expanded_matched_default_metrics.json').exists():
 dm=json.loads((ROOT/'delta_interpretation/expanded_matched_default_metrics.json').read_text())
 delta_section=['## Completed investigation of all delta outliers','','All 280 top-20 delta entries across 14 descriptors now identify both native extremizers, exact input hashes, independent per-conformer values and complete reference-ensemble reductions. An additional frozen campaign covers every conformer of all 77 ligands among the buried-volume delta outliers: 2,009 conformers, with 218 exact records reused from the previous frozen campaign and 1,791 newly computed. The authoritative combined 1,120-entry dossier is `delta_interpretation/all_top20_outlier_dossiers.json`; the earlier derivative is preserved. No reported main-comparison input was removed.','','Across the union of both diagnostic campaigns, matched default-grid direct Morfeus comparisons cover 2,372 native-success cases. Additional boundary-sensitive cases broaden the numerical limits beyond the earlier 581-case sample:','','| Field | N | Maximum matched error | Exact case |','|---|---:|---:|---|']
 for field,val in dm.items():delta_section.append(f"| {field} | {val['N']} | {val['maximum_absolute_error']:.17g} | {val['maximum_case']['id']} |")
 delta_section += ['','Absolute volumes use Å³; percent buried volume uses percentage points. The largest total and percent differences correspond to approximately one default integration-cell weight. These cases remain part of the quantified arithmetic/frame-boundary limitation, rather than being discarded as outliers.','','Ligand 369 illustrates a different problem. Native total-volume delta is 76.17142486572266 Å³ versus published 66.37206347 Å³. Independent Morfeus with the native convention gives 76.17142221556755 Å³, whereas the original center/density gives 76.73697859460583 Å³. Thus its large published discrepancy is not explained by the native occupancy algorithm. All 84 exported geometries have the same canonical connectivity graph as the API SMILES when unspecified stereotags are excluded. SDF conversion adds stereotags to adamantyl cages that the API SMILES leaves unspecified. The API IDs form two contiguous blocks: 38367–38410 (44 conformers) and 64409–64448 (40). The latter contains conformer 64422, which sets the larger maximum. As a diagnostic only, the first block gives primary total delta 66.37310937335505 Å³ and far-hemisphere delta 56.1650799456219 Å³, within 0.001046 and 0.004184 Å³ of the published values. All 84 remain in the main comparison. This supports an ensemble mismatch; ID ordering alone does not prove insertion dates or the original reason for inclusion/exclusion. Exact geometry, graph, donor, center and block evidence is in `delta_interpretation/ligand_369_dossier.json`.','','Other remaining primary-reference delta discrepancies, including ligands 1290 and 1805, remain explicitly UNCERTAIN in the dossiers. Four untuned complete-ensemble variants quantify center/grid effects separately. The primary `read_ligand` source removes calculation errors/imaginary-frequency structures and energy/RMSD duplicates before aggregation; per-property missing values can also reduce its extrema set. The current public exports lack the original selection/error/energy records. Our strict complete-available-geometry audit is therefore reproducible but cannot assert identity with every original retained calculation ensemble.','','']
 text=text.replace('## Remaining published-value outliers','\n'.join(delta_section)+'## Remaining published-value outliers')
(ROOT/'REPORT.md').write_text(text)
save(ROOT/'report_manifest.json',{'created_utc':datetime.datetime.now(datetime.UTC).isoformat(),'generator_sha256':sha(Path(__file__)),'report_sha256':sha(ROOT/'REPORT.md'),'source_metric_hashes':{str(p.relative_to(ROOT)):sha(p) for p in [ROOT/'analysis/metrics.json',ROOT/'interpretation/direct_morfeus_metrics.json',ROOT/'interpretation/same_center_analytic_metrics.json',ROOT/'interpretation/headline_outlier_dossiers.json']}})
