#!/usr/bin/env python3
"""Investigate largest BV delta outlier without removing any comparison input."""
import json,datetime
from pathlib import Path
from rdkit import Chem
from kraken_analyze import ROOT,save,sha
rows=[v for v in map(json.loads,(ROOT/'delta_outliers/reference_raw.jsonl').open()) if v['id'].split(':')[1]=='369'];pub={v['property']:v for v in json.loads((ROOT/'primary/published_dft/369.body').read_text())};meta=json.loads((ROOT/'primary/molecule/369.body').read_text());canonical_expected=Chem.MolToSmiles(Chem.MolFromSmiles(meta['smiles']),isomericSmiles=False);graphs=[]
for row in rows:
 cid=int(row['id'].split(':')[-1]);p=ROOT/'primary/conformers'/f'{cid}.body';mol=Chem.MolFromMolBlock(p.read_text(),removeHs=True);sm=Chem.MolToSmiles(mol);graphs.append({'id':row['id'],'input':str(p.relative_to(ROOT)),'sha256':sha(p),'canonical_smiles':sm,'canonical_connectivity_smiles':Chem.MolToSmiles(mol,isomericSmiles=False),'matches_API_connectivity_smiles':Chem.MolToSmiles(mol,isomericSmiles=False)==canonical_expected,'stereochemistry_note':'API SMILES lacks some cage stereotags assigned by SDF/3D conversion; connectivity comparison explicitly omits stereotags.','primary_donor':row['primary_donor'],'input_donor':row['input_donor'],'primary_neighbors':row['primary_neighbors'],'SDF_neighbors':row['topological_neighbors'],'center_angle_degrees':row.get('center_angle_degrees')})
blocks=[]
for name,subset in [('all_84_retained_main_comparison',rows),('API_ID_block_38367_to_38410',[v for v in rows if 38367<=int(v['id'].split(':')[-1])<=38410]),('API_ID_block_64409_to_64448',[v for v in rows if 64409<=int(v['id'].split(':')[-1])<=64448])]:
 stats={}
 for field,prop in [('buried_volume','vbur_vbur'),('far_vbur','vbur_far_vbur')]:
  pairs=[(v['id'],v['primary_0001'][field]) for v in subset];lo=min(pairs,key=lambda p:p[1]);hi=max(pairs,key=lambda p:p[1]);delta=hi[1]-lo[1];stats[field]={'minimum':lo,'maximum':hi,'delta':delta,'published_delta':pub[prop]['delta'],'delta_residual':delta-pub[prop]['delta']}
 blocks.append({'block':name,'N':len(subset),'stats':stats})
record={'created_utc':datetime.datetime.now(datetime.UTC).isoformat(),'script_sha256':sha(Path(__file__)),'failing_inputs':graphs,'SUT_results':'delta_interpretation/delta_outlier_dossiers.json:buried_volume_delta/far_vbur_delta ligand369','independent_results':blocks,'reference_definition':'Original raw-vector center at2.28Å;Bondi1.17;H excluded;sphere3.5Å;density0.001;lastorientation totals/hemispheres;delta=max−min over retained source calculation ensemble.','primary_ensemble_selection':'Frozen original read_ligand removes error/imaginary-frequency conformers and energy/RMSD duplicates before calculating properties. Public API has no matching selection/error/energy records.','likely_cause':'SUPPORTED mismatch between currently exported full ensemble and ensemble underlying published descriptors. All84geometries have identical canonical connectivity graph matching API SMILES after excluding unspecified stereotags. The lower-ID contiguous44conformer block independently reproduces published total/far delta within0.00105/0.00419Å³;the40conformer otherblock containsnew maxima. ContiguousIDblocks are descriptive only; insertiondates orwhy excluded cannot be inferred without source records.','scientific_magnitude':'Usingall84conformers:primary-convention versuspublished BVdelta10.36491512460583Å³ andfardelta10.36700693945405Å³. Native deltaerrors9.799361395722656/9.744944852170413Å³;matchedindependentkernel reproducesnative to6.23e−6Å³.','affected_claims':['K01','K02','K03','K14'],'proposed_correction':'Qualify corpus/ensemble identity; obtain historical conformer inclusion/error/energy records before changing calculations or reference data. Do not remove the40conformer block to improve headline metrics; main results retainall84.','classification':'SUPPORTED ensemble-mismatch explanation; exact provenance/correct historical inclusion remainsUNCERTAIN.'}
save(ROOT/'delta_interpretation/ligand_369_dossier.json',record)
print('allcanonicalmatch',all(v['matches_API_connectivity_smiles'] for v in graphs))
